//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int idAttachment { get; set; }
        public byte[] attachment1 { get; set; }
        public string name { get; set; }
        public string ext { get; set; }
        public Nullable<int> idProject { get; set; }
        public Nullable<int> idTask { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Task Task { get; set; }
    }
}
