//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMembersView
    {
        public string projectName { get; set; }
        public string projectDescription { get; set; }
        public string area { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int idProject { get; set; }
        public int idMember { get; set; }
        public string netID { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string displayName { get; set; }
    }
}
