//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMember
    {
        public int idProjectMember { get; set; }
        public int idProject { get; set; }
        public int idMember { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Project Project { get; set; }
    }
}
