//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksView
    {
        public string taskName { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string status { get; set; }
        public string projectName { get; set; }
        public string area { get; set; }
        public int idTask { get; set; }
        public int idProject { get; set; }
    }
}
