//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAttachment
    {
        public int idAttachment { get; set; }
        public byte[] attachment { get; set; }
        public string name { get; set; }
        public int idProject { get; set; }
        public string projectName { get; set; }
        public int idTask { get; set; }
        public string taskName { get; set; }
    }
}
