//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VChanx
    {
        public int idVC { get; set; }
        public string plant { get; set; }
        public string material { get; set; }
        public string projectName { get; set; }
        public string oldVendor { get; set; }
        public string newVendor { get; set; }
    }
}
